### PR TITLE
[AutoPublisher] feat: ignore channels

### PR DESCRIPTION
**Pull request by japandotorg**
~~- add channels config so that autopublisher only publishes messages in selected/specific channels and not all the news channels.~~
- add channels config so that autopublisher is ignored in selected/specified channels.

### CODE REVIEW

**Review by ltzmax — COMMENTED** [review]
I already had planned to add a `[p]autopublisher ignorechannels` since i still want it to publish automatically without having to add every channels you want it to send from. So instead of add, I'll prefer it ignoreing the channels.

**Comment by japandotorg** [comment]
Done!

**Review by ltzmax — CHANGES_REQUESTED** [review]
Thanks, just missing two things now. Docs in README.md and showing ignored channels in `[p] autopublisher view`

Could also use `usage="<add_or_remove>"` since current look like this `<"add"|"remove">` and it's not good looking.

**Comment by japandotorg** [comment]
It's done!

**Review by ltzmax — APPROVED** [review]
Thanks. ill fix the autopublisher view to not stay empty when none ignored myself!

**Pull request merged**
