### PR TITLE
enhancements

### PR DESCRIPTION
**Pull request by japandotorg**

### CODE REVIEW

**Review by ltzmax — CHANGES_REQUESTED** [review]
Everything worked expect `whosthatpokemon`, the timeout became 30sec delayed to timeout.
- in same cog, there's a info.json line `THIS IS A DEVELOPER VERSION OF THE COG AND MAY NOT WORK CORRECTLY.` which can be removed.

**Comment by japandotorg** [comment]
> Everything worked expect `whosthatpokemon`, the timeout became 30sec delayed to timeout.
I see, is that because of the `self.message: discord.Message = None` ? I have seen you around playing with the buttons of this cog, trying to fix it, did you intentionally didn't have `self.message` in the `__init__` ?

**Comment by ltzmax** [comment]
> > Everything worked expect `whosthatpokemon`, the timeout became 30sec delayed to timeout.
> 
> I see, is that because of the `self.message: discord.Message = None` ? I have seen you around playing with the buttons of this cog, trying to fix it, did you intentionally didn't keep `self.message` in the `__init__` ?

Yeah, i dropped that self.message since it wasn't used / needed. kreu didn't made me use it either from his qa review so, and it's made from flame! :P

**Comment by japandotorg** [comment]
Thanks! That should be it.

**Review by ltzmax — APPROVED** [review]
Thanks for the pr! 👍

**Pull request merged**
